- defaults:
    link:
      relink: true
      create: true
      force: true
    shell:
      stdout: true
      stderr: true

- create:
    - $HOME/.config

- link:
    ~/.aliases: .aliases
    ~/.exports: .exports

- clean:
    $HOME:
        force: true
    $HOME/.config:
        recursive: true
